// data.js
export const foodItems = [
  {
    id: "001",
    name: "Margherita Pizza",
    price: 8.99,
    status: "Active",
    type: "Veg",
    category: "Pizza",
  },
  {
    id: "002",
    name: "Chicken Burger",
    price: 6.49,
    status: "Active",
    type: "Non-Veg",
    category: "Burger",
  },
  {
    id: "003",
    name: "Paneer Tikka",
    price: 5.99,
    status: "Inactive",
    type: "Veg",
    category: "Curry",
  },
  {
    id: "004",
    name: "Veggie Sandwich",
    price: 4.99,
    status: "Active",
    type: "Veg",
    category: "Snack",
  },
  {
    id: "115",
    name: "Grilled Fish",
    price: 9.99,
    status: "Active",
    type: "Non-Veg",
    category: "Curry",
  },
  {
    id: "126",
    name: "Caesar Salad",
    price: 5.49,
    status: "Inactive",
    type: "Veg",
    category: "Salad",
  },
  {
    id: "7",
    name: "Mutton Curry",
    price: 10.99,
    status: "Active",
    type: "Non-Veg",
    category: "Curry",
  },
  {
    id: "8",
    name: "Veg Biryani",
    price: 7.49,
    status: "Active",
    type: "Veg",
    category: "Rice",
  },
  {
    id: "9",
    name: "Chicken Wings",
    price: 8.49,
    status: "Inactive",
    type: "Non-Veg",
    category: "Snack",
  },
  {
    id: "10",
    name: "Chocolate Cake",
    price: 3.99,
    status: "Active",
    type: "Veg",
    category: "Dessert",
  },
];
